name: Build and Release

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      # 检查MSVC构建工具（镜像已预装Visual Studio 2022）
      - name: Verify MSVC Tools
        shell: cmd
        run: |
          vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64

      # Node.js 缓存
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-


      # 缓存Cargo依赖
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~\.cargo\registry
            ~\.cargo\git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # 安装项目依赖
      - name: NPM Install
        run: npm install

      # 构建Tauri应用
      - name: Build with Tauri
        run: npm run tauri build
        env:
          VCPKG_INSTALLATION_ROOT: ${{ env.VCPKG_INSTALLATION_ROOT || 'C:\vcpkg' }}  # 使用镜像预配置路径
          CI: false

      # 发布产物（使用v4版本）
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build
          path: src-tauri/target/release/
          if-no-files-found: error
          retention-days: 5
          overwrite: true
